# Project information
site_name: Wenfeng
site_description:
site_author: Wenfeng Zhuo
site_url: https://wenfengzhuo.github.io

# Copyright
copyright: Copyright &copy; 2016 - 2020 Wenfeng Zhuo

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  custom_dir: overrides

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/squidfunk
  disqus: wenfengzhuo
  footer_nav: false

# Google Analytics
google_analytics:
  - UA-128750316-1
  - auto

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - meta
